# Generated by Django 3.2.8 on 2021-10-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('album_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('album_link', models.CharField(max_length=200)),
                ('album_type', models.CharField(max_length=100)),
                ('album_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artist_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('artist_followers', models.PositiveIntegerField()),
                ('artist_genres', models.CharField(max_length=500)),
                ('artist_name', models.CharField(max_length=200)),
                ('artist_popularity', models.PositiveIntegerField()),
                ('artist_uri', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groover_api.albums')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groover_api.artists')),
            ],
        ),
    ]
