# Generated by Django 3.2.8 on 2021-10-13 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groover_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapping',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='mapping',
            name='artist_id',
        ),
        migrations.AddField(
            model_name='artists',
            name='release_date',
            field=models.DateField(default=datetime.date(2021, 10, 13)),
        ),
        migrations.DeleteModel(
            name='Albums',
        ),
        migrations.DeleteModel(
            name='Mapping',
        ),
    ]
