# Generated by Django 3.2.8 on 2021-10-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groover_api', '0004_auto_20211018_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='artist_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist_genres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist_popularity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
